# Generated by Django 3.2.4 on 2021-06-23 07:43

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0005_building'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(geography=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='gangnam',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(geography=True, null=True, srid=4326),
        ),
    ]
